In [2]:
def diffs(probas):
    return [
        abs(sum1 - sum2)
        for sum1, sum2 in [
            (
                sum(probas[:i]),
                sum(probas[i:])
            )
            for i in range(1, len(probas))
        ]
    ]

In [3]:
def diffs2(probas):
    probas = np.array(probas)
    left_sums = np.cumsum(probas)[:-1]
    total_sum = np.sum(probas)
    right_sums = total_sum - left_sums
    differences = np.abs(left_sums - right_sums)
    return differences.tolist()

In [4]:

import numpy as np  
# create a very large array with random values using numpy
arr = np.random.rand(2**8)

assert np.allclose(diffs(arr), diffs2(arr))

In [5]:
%%timeit
diffs(arr)

4.98 ms ± 9.1 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
%%timeit
diffs2(arr)

12.7 μs ± 446 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [7]:
5120 / 12.6

406.3492063492064

In [8]:
1300/40

32.5

In [9]:
1700/20

85.0

In [10]:
arr

array([0.79788259, 0.64276464, 0.11290003, 0.01573327, 0.70131714,
       0.04771457, 0.9851833 , 0.55986726, 0.31186899, 0.63835788,
       0.80724948, 0.19017187, 0.62715659, 0.03057214, 0.91613175,
       0.1398169 , 0.34744688, 0.46764399, 0.40040492, 0.26441572,
       0.30887585, 0.85757919, 0.28780751, 0.01762907, 0.90637026,
       0.99852545, 0.78002936, 0.45869347, 0.82495207, 0.91388376,
       0.78227867, 0.45581737, 0.75515594, 0.75939634, 0.07491185,
       0.11108895, 0.88240319, 0.96781427, 0.1948758 , 0.67318219,
       0.77214767, 0.02348293, 0.74899045, 0.36437357, 0.26324169,
       0.97915585, 0.02357678, 0.02286273, 0.09855265, 0.76239778,
       0.84575143, 0.91815225, 0.70049647, 0.1149616 , 0.96441243,
       0.47711736, 0.04092546, 0.8703117 , 0.34480492, 0.04416617,
       0.50226671, 0.2656902 , 0.87662143, 0.67127965, 0.37582962,
       0.44707883, 0.92187995, 0.34932466, 0.47713441, 0.46881939,
       0.82564135, 0.01364737, 0.36799096, 0.04856049, 0.59189

In [11]:
%%timeit
sorted(arr)

47.5 μs ± 2.42 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [12]:
%%timeit
np.sort(arr)

3.58 μs ± 429 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [17]:
file = "probas_and_idxs.pkl"
import pickle

# load the data
with open(file, "rb") as f:
    data = pickle.load(f)

In [25]:
%%timeit
-np.sort(-data, axis=1, kind="heapsort")

11.5 μs ± 2.05 μs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [26]:
%%timeit
-np.sort(-data, axis=1, kind="quicksort")

12.6 μs ± 810 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [28]:
%%timeit
-np.sort(-data, axis=1, kind="mergesort")

17.7 μs ± 2.51 μs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [29]:
%%timeit
sorted(data, key=lambda t: t[0], reverse=True)

463 μs ± 2.05 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [50]:
data.T[0].argsort()

array([862, 810, 389, 392,  62, 746,  58, 865, 686, 394, 251,  43,  42,
       781, 506,  53, 800, 320, 564, 121, 118, 371, 547, 751, 200, 365,
       839, 103, 535,  98, 422,  89, 228, 128, 263, 880, 969, 652, 274,
       980, 592, 414, 784,  18, 515,  30, 271, 798, 407, 606, 718, 786,
       773, 424, 245, 224, 342, 412, 949, 264, 738, 898,  46, 597, 190,
       464, 219, 119, 159, 645, 417, 719, 970, 816, 206, 483,  10, 370,
       845, 332, 950, 722, 346, 923, 495, 252, 443, 249, 449,  26, 248,
        56, 500, 230, 885, 141, 747, 774, 691, 875, 692, 403, 354, 234,
       243, 985, 680, 124, 114, 112, 135, 727, 871, 978, 567, 937, 431,
       475, 943, 152, 525, 538, 613, 146, 420, 831, 568, 709, 258, 678,
        88,  93, 829, 674, 409,  19, 843, 649, 730, 608, 888, 578, 156,
       866, 208, 729, 244, 681, 321, 223, 771, 300, 343, 203, 735, 689,
       699, 290, 484, 817, 401, 402, 828, 404, 473, 372,  97, 724, 560,
       212, 851, 726, 824, 376, 480, 221, 792, 754, 539, 837, 56

In [57]:
x = """[122  21 570 172 386 589 383 893 661 637 643 166 973 594 399 671 601 841
 384   2 575 175 957 942 526 218 186 419  50 600 940 211 556 302 142 647
 549 445 808 367  49  12  71 639 239 485 625 696 294 579 756 545 648 397
 276 666 783 734 859 688 917 602 214 660 369 848 474 334  38 331 170 353
 330  11 410 605 289 988  34 467 247 225 777 246 737 788 596 496  57 768
 873 627 297 147 587 685 944 960 478 918 708 440 358 381 936 418  48 487
 268 897 812 299 366 110 693 161 261  59 481 185 428 758 876 630 607 887
 265 113  70 814 716 293 883  80 270 702   4 111 275 158 157 233 347 789
 617 335 125 368 941 254 204 357 916 477 413 842 187 964 497  84 436 441
 920 168 640 458  73 705  36 406 926 183 405 460 972 311  75 599 947 900
 803 572 598 189 164 351 745 266 216 322 614 415 921 393 536 352 255 826
 922 930 799 958  20 430 502 934 740 272 469 793 105 581   1 870 700 398
 304 109 267 832 665 149 707 551 447 710 145 345 677 421 309 519  60 558
 979 150 892 877 359   3 325  41 196 588 907 690 378 192 664  99 836 333
 423 298 541 838 363 240 976 425 687 663 765 634 324 962  32 698 511 867
 492 282 380 540 967  45 148 528 364 514 582 743 242 821 844 437 522 523
 307 913 654 530 182 646 928 361 301 108 562 426 438 626 658 154 697 987
 762 482 825 508 715 375  78 120 532 609 655  83 524 130 952 250 373 796
 804 945 787 732 193 823 306 670 633 215 951 202 618 704 651 974 442 714
 374 106 752 584 863 194 169 195 360 569 755 961 328 628 807 117 905 344
 479 566 585 580  28 938 642 683 977 955 197 178  90 337 882  67 491 550
 507 336 350 894   6 472 315 975 533 432 906 534  25 377 759 679 288 132
 622 285 286 815 235 790 864 749 531 858 446 262 382 760 280 713  15 903
 846 631 411 778 573 616 728 340 529 454 879 433 318 932 516 162 466 101
 456 927 968 632  68 329 590 811 741 948 675 668 619 909 284 292  33 954
   8 518  61   9 455 388 391 210 327 813 278 703 379 444 557 981 283 143
 144 476 856  13  24 603  37 542 102 914 635 548 131 253 850 462 891 753
 953 731 779 889  74 177 986  35 775  79 179  39 281 295 636 452 966 205
  92 711 931 706 676 259 180 348 884 498  31 499 657 902 313 236 173 766
 488 849  94 761 512 501 213 868  14  96 641 238  47 188 910 833 984 971
 744 750  40 881 956 723 163 615 795 939 140 355 555 827 669 820 305 387
 226 291 503  72 326 123 279 416 341 217 494 847 860 878 229  52 459 527
 100 682 806 591 819 461 912 155 574 857 323 356 896 134 504 395 317 451
  87 453 794 695 929 982 965 620 653 312 116 717 338 115  64 269 809 748
 586 770 171 174 611 933 935  29  65 396 544 701 546 470 854 780 465 672
 739 650 537 513 593   0 434 429 198 785 797 895  22 662 853 554 565 818
 673 191 232 595 184 659 576 667 763 604 181 621 237  69 583 138 801  16
 963 127 644 624 427 287 139 830 362 915  51 861 448  86 852 725 505 720
 919 521 319 136 435 577 339 925 167 712 220 612 769 165 209 314 408 450
 385 835 107 983  55 151 471 390 855  27 133 509 231 874 886  54 207 486
  76 767  85  81  82 764 899 126 468 559 721 736 733 199 757 890 349 493
 924 439 273 490 517 303 160   5 946 742  17 222 296 553 129 610 802 463
 822  44 911 260 901 904 256 257 908  63 137 840 241 772 316 872 869 571
 457 176 489 782 153 510 791  91  23 684 561 543 310  95 638 201 552  66
 834 104   7 623 694 629 400 776 308 959 520 227 656 277  77 805 563 837
 539 754 792 221 480 376 824 726 851 212 560 724  97 372 473 404 828 402
 401 817 484 290 699 689 735 203 343 300 771 223 321 681 244 729 208 866
 156 578 888 608 730 649 843  19 409 674 829  93  88 678 258 709 568 831
 420 146 613 538 525 152 943 475 431 937 567 978 871 727 135 112 114 124
 680 985 243 234 354 403 692 875 691 774 747 141 885 230 500  56 248  26
 449 249 443 252 495 923 346 722 950 332 845 370  10 483 206 816 970 719
 417 645 159 119 219 464 190 597  46 898 738 264 949 412 342 224 245 424
 773 786 718 606 407 798 271  30 515  18 784 414 592 980 274 652 969 880
 263 128 228  89 422  98 535 103 839 365 200 751 547 371 118 121 564 320
 800  53 506 781  42  43 251 394 686 865  58 746  62 392 389 810 862]"""[1:-1].split()

In [59]:
x = np.array(x, dtype=int)

In [61]:
x.shape

(989,)

In [53]:
data.T[0][122], data.T[0][862]

(np.float64(0.005913607729905397), np.float64(0.0029021594585654192))

In [41]:
np.argsort(-data[:, 1])

array([988, 987, 986, 985, 984, 983, 982, 981, 980, 979, 978, 977, 976,
       975, 974, 973, 972, 971, 970, 969, 968, 967, 966, 965, 964, 963,
       962, 961, 960, 959, 958, 957, 956, 955, 954, 953, 952, 951, 950,
       949, 948, 947, 946, 945, 944, 943, 942, 941, 940, 939, 938, 937,
       936, 935, 934, 933, 932, 931, 930, 929, 928, 927, 926, 925, 924,
       923, 922, 921, 920, 919, 918, 917, 916, 915, 914, 913, 912, 911,
       910, 909, 908, 907, 906, 905, 904, 903, 902, 901, 900, 899, 898,
       897, 896, 895, 894, 893, 892, 891, 890, 889, 888, 887, 886, 885,
       884, 883, 882, 881, 880, 879, 878, 877, 876, 875, 874, 873, 872,
       871, 870, 869, 868, 867, 866, 865, 864, 863, 862, 861, 860, 859,
       858, 857, 856, 855, 854, 853, 852, 851, 850, 849, 848, 847, 846,
       845, 844, 843, 842, 841, 840, 839, 838, 837, 836, 835, 834, 833,
       832, 831, 830, 829, 828, 827, 826, 825, 824, 823, 822, 821, 820,
       819, 818, 817, 816, 815, 814, 813, 812, 811, 810, 809, 80

In [38]:
arr.T

array([0.79788259, 0.64276464, 0.11290003, 0.01573327, 0.70131714,
       0.04771457, 0.9851833 , 0.55986726, 0.31186899, 0.63835788,
       0.80724948, 0.19017187, 0.62715659, 0.03057214, 0.91613175,
       0.1398169 , 0.34744688, 0.46764399, 0.40040492, 0.26441572,
       0.30887585, 0.85757919, 0.28780751, 0.01762907, 0.90637026,
       0.99852545, 0.78002936, 0.45869347, 0.82495207, 0.91388376,
       0.78227867, 0.45581737, 0.75515594, 0.75939634, 0.07491185,
       0.11108895, 0.88240319, 0.96781427, 0.1948758 , 0.67318219,
       0.77214767, 0.02348293, 0.74899045, 0.36437357, 0.26324169,
       0.97915585, 0.02357678, 0.02286273, 0.09855265, 0.76239778,
       0.84575143, 0.91815225, 0.70049647, 0.1149616 , 0.96441243,
       0.47711736, 0.04092546, 0.8703117 , 0.34480492, 0.04416617,
       0.50226671, 0.2656902 , 0.87662143, 0.67127965, 0.37582962,
       0.44707883, 0.92187995, 0.34932466, 0.47713441, 0.46881939,
       0.82564135, 0.01364737, 0.36799096, 0.04856049, 0.59189